### PR TITLE
Add tw_lookup

### PR DESCRIPTION
**Pull request by yogat3ch**
- Add `tw_lookup` that uses the [Twilio Lookup API](https://www.twilio.com/docs/lookup) to determine if a number is valid
- Re-render docs with roxygen

### CODE REVIEW

**Comment by sumtxt** [comment]
Thank you for adding this function. This is great. I am happy to pull if i) you remove all .Rd files from the commit and ii) move parse_lookup() to the file tw_lookup.R (instead of check_status.R).

**Comment by yogat3ch** [comment]
> Thank you for adding this function. This is great. I am happy to pull if i) you remove all .Rd files from the commit and ii) move parse_lookup() to the file tw_lookup.R (instead of check_status.R).

Ok, will do this today!

**Comment by yogat3ch** [comment]
Ok, done! 
I'm wondering why you don't want the `.Rd` files? Do they build automatically when someone installs the package and you save some space by not including them - or do you just not like the way the newer version of Roxygen builds the documentation?

**Comment by sumtxt** [comment]
Thanks again for this new code. I pulled it into the master and made a few revisions to the documentation and the code. Nothing major. RE `.Rd` files: They were not part of the repo which is weird but I added them now.

**Comment by yogat3ch** [comment]
No problem! Thanks for fixing that bug in the original package! Good to know RE the `Rd` files - I thought there might be some efficiency or something that I wasn't aware of but I guess not!

**Pull request merged**
